### ISSUE TITLE
feat: typographies should not have predefined colors

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#129]
### Feature Description

All typographies in the` libs/anglify/src/styles/settings/typography.scss` file define the text colors themselves. This should be removed so that the respective components can define the colors themselves (because it depends on the background color).

**Current behavior:**
```scss
.title-s {
  font-weight: 500;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.1px;
  color: var(--color-on-surface-high-emphasis);
}
```

**New behavior:**
```scss
.title-s {
  font-weight: 500;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.1px;
}
```

### Use Case

The title color of the toolbar must then also be adjusted
